---
- name: gather info from routers
  hosts: cisco
  gather_facts: no
  
  tasks:
  - name: gather router facts
    cisco.ios.facts:
      gather_subset: all
    register: result
    
 - name: Save router facts to txt file
   ansible.builtin.copy:
     content: "{{ result }}"
     dest: /router-facts/{{ inventory_hostname }}_facts.txt
   delegate_to: localhost
    
  - name: display version
    debug:
      msg: "The IOS version is:  {{ ansible_net_version }}" 
      
  - name: display serial number
    debug:
      msg: "The serial number is: {{ ansible_net_serialnum }}"
